package trestview.menu;

public enum MenuItemCall {defaultItem, testOfMachineItem, resourcesLinksPerspectiveItem, conveyorSpeedConstantItem, conveyorSpeedDependsTimeItem, routePerspectiveItem, orderPlaninigPerspectiveItem}